name: Docker Image CI

# Were we can define the inputs that our action will accept


runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
  - name: Build the Docker image
    #uses: somelibrary/deploy@master
    run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

