# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Azure Devops Pipeline that build and publish an image, than uses ASC 
# scan results to determines the health of the pipeline.
# Enrich Image publish with test of it's scan result to assess if to fail or pass pipeline by scan findings severity.
# This Gate can also be used as a gate for production registry as a pre condition step to publish the image to secure registry.

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  # Read more here: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#create-a-service-connection
  dockerRegistryServiceConnection: 'acr_registry'
  imageRepository: 'imagescan1'
  containerRegistry: 'myregistrydemo1'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  waitForScanResultsAfterPushInMinutes: '2'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build_and_Publish
  displayName: Build and push image to registry than check for vulnerability scan results to determine publishing health
  jobs:
  # Build Image and push it to on-boarded to ASC ACR registry
  - job: BuildAndPush
    displayName: BuildAndPush
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        addPipelineData: false
        tags: |
          $(tag)
          latest
          
    # Wait till ASC vulnerability scan will be completed for pushed image
  - job: WaitForScanResults
    displayName: Wait for Scan result
    pool: Server
    dependsOn: 
    - BuildAndPush
    condition: succeeded()
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: $(waitForScanResultsAfterPushInMinutes)
    
    # Run Image scan gate - which extracts image scan results and assess whether 
    # to fail the pipeline based on severity threshold configuration.
    # Using the ImageScanSummaryAssessmentGate.ps1 script in same repo folder
  - job: ImageScanGate
    displayName: Image Scan security gate
    pool:
      vmImage: $(vmImageName)
    dependsOn: 
    - BuildAndPush
    - WaitForScanResults
    steps:
    # Read more here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial (7efefb00-e17c-4d85-a4ce-d13264a86786)'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        # Security Gate powershell script in same folder
        scriptPath: '$(Build.SourcesDirectory)/ImageScanSummaryAssessmentGate.ps1'
        arguments: '-registryName $(containerRegistry) -repository $(imageRepository) -tag $(tag)'
      
