name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: ${{ github.event.workflow_run.head_branch }}
    - name: Build the Docker image
      uses: "./.github/Template"
      with:
       tag: $GITHUB_RUN_NUMBER
